# -*- coding: utf-8 -*-
"""20230927_simple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eUiplpXy7PPlzjXmkhjRUHVyd_Kk6Z8n

# Regresión Lineal Simple

## Importar las librerías
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importar los datasets"""

dataset = pd.read_csv('/Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#from google.colab import drive
#drive.mount('/content/drive')

"""## Dividir el dataset entre conjuntos de entrenamiento y testing"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

"""## Entrenar el modelo de Regresión Lineal Simple usando el conjunto de entrenamiento"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""## Predecir los resultados de test"""

y_pred = regressor.predict(X_test)

"""## Visualizar los resultados en el conjunto de entrenamiento"""

plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Sueldo vs Experiencia (Conjunto de Entrenamiento)')
plt.xlabel('Años de Experiencia')
plt.ylabel('Sueldo')
plt.show()

"""## Visualizar los resultados en el conjunto de testing"""

plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Sueldo vs Experiencia (Conjunto de Test)')
plt.xlabel('Años de Experiencia')
plt.ylabel('Sueldo')
plt.show()